/**
 * Markdown manifest generation (docs/litematic-export-spec.md §8, phase 3).
 *
 * A readability companion to infinote.json and the in-game tuning reference
 * sheet: placement settings, per-track geometry, the base block / sound /
 * pitch correspondence tables, and the dB-error report.
 */
import type { Song } from "../model/types"
import { VANILLA_BASE_BLOCKS } from "../model/song"
import type { GenerateOptions } from "./generate"
import type { PlacementResult } from "./placement"
import { decomposeKey, isVanillaPlayable } from "./slots"

export interface ManifestSlotRow {
  blockId: string
  soundId: string
  pitchShift: number
  count: number
}

export interface ManifestVanillaRow {
  instrument: string
  blockId: string
  count: number
}

export interface ManifestInput {
  songName: string
  generatedAt: Date
  options: GenerateOptions
  placement: PlacementResult
  slotRows: ManifestSlotRow[]
  vanillaRows: ManifestVanillaRow[]
  /** Warnings gathered by the export flow (stereo samples, conflicts, …). */
  warnings: string[]
}

/** Vanilla-playable note counts per instrument for the included layers. */
export function collectVanillaUsage( song: Song, layerIds: ReadonlySet< string > ): ManifestVanillaRow[] {
  const counts = new Map< string, number >()
  for ( const layer of song.layers ) {
    if ( ! layerIds.has( layer.id ) ) continue
    for ( const note of layer.notes ) {
      const inst = song.instruments[ note.instrument ]
      if ( ! inst?.isVanilla || ! inst.vanillaId ) continue
      if ( ! isVanillaPlayable( inst, decomposeKey( note.key, inst.pitchKey, note.pitch ) ) ) continue
      counts.set( inst.vanillaId, ( counts.get( inst.vanillaId ) ?? 0 ) + 1 )
    }
  }
  return [ ...counts.entries() ]
    .map( ( [ instrument, count ] ) => ( {
      instrument,
      blockId: VANILLA_BASE_BLOCKS[ instrument as keyof typeof VANILLA_BASE_BLOCKS ] ?? "?",
      count
    } ) )
    .sort( ( a, b ) => ( a.instrument < b.instrument ? -1 : 1 ) )
}

const shiftText = ( shift: number ): string => ( shift > 0 ? `+${ shift }` : String( shift ) )

export function buildManifest( input: ManifestInput ): string {
  const { options, placement } = input
  const lines: string[] = []
  const push = ( s = "" ) => lines.push( s )

  push( `# ${ input.songName } — litematic export manifest` )
  push()
  // sv-SE formats as local-time YYYY-MM-DD.
  push( `Generated by DNW on ${ input.generatedAt.toLocaleDateString( "sv-SE" ) }.` )
  push()

  push( "## Placement settings" )
  push()
  push( "| Setting | Value |" )
  push( "|---|---|" )
  push( `| Placement side | ${ options.side } |` )
  push( `| First track depth | ${ options.firstDepth } |` )
  push( `| Track spacing | ${ options.spacing } |` )
  push( `| Velocity curve α | ${ options.alpha } |` )
  push( `| Mixer volumes applied | ${ options.applyMixerVolumes ? "yes" : "no" } |` )
  push( `| tp rotation fixed | ${ options.includeRotation ? "yes (yaw -90)" : "no" } |` )
  push( `| Tempo row depth | ${ options.tempoDepth } |` )
  push()

  push( "## Tracks" )
  push()
  push( "| # | Track | Side | Depth | Notes | Max lateral | Notes > 1 dB |" )
  push( "|---|---|---|---|---|---|---|" )
  placement.tracks.forEach( ( track, i ) => {
    const over = track.placed.filter( ( p ) => p.dbError > 1 ).length
    push(
      `| ${ i + 1 } | ${ track.name } | ${ track.noteY < 0 ? "below" : "above" } | ${ track.depth } | ` +
        `${ track.placed.length } | ±${ track.maxAbsDz } | ${ over } |`
    )
  } )
  push()

  push( "## Block mappings" )
  push()
  if ( input.slotRows.length > 0 ) {
    push( "infinote config slots (also written to infinote.json):" )
    push()
    push( "| Base block | Sound | Pitch shift | Notes |" )
    push( "|---|---|---|---|" )
    for ( const row of [ ...input.slotRows ].sort( ( a, b ) =>
      a.soundId === b.soundId ? a.pitchShift - b.pitchShift : a.soundId < b.soundId ? -1 : 1
    ) ) {
      push( `| ${ row.blockId } | ${ row.soundId } | ${ shiftText( row.pitchShift ) } | ${ row.count } |` )
    }
    push()
  }
  if ( input.vanillaRows.length > 0 ) {
    push( "Vanilla note blocks (no config needed):" )
    push()
    push( "| Base block | Instrument | Notes |" )
    push( "|---|---|---|" )
    for ( const row of input.vanillaRows ) {
      push( `| ${ row.blockId } | ${ row.instrument } | ${ row.count } |` )
    }
    push()
  }
  if ( input.slotRows.length === 0 && input.vanillaRows.length === 0 ) {
    push( "No notes were placed." )
    push()
  }

  push( "## Placement error" )
  push()
  const offenders = placement.tracks
    .flatMap( ( track ) => track.placed.map( ( p ) => ( { track: track.name, ...p } ) ) )
    .filter( ( p ) => p.dbError > 1 )
    .sort( ( a, b ) => b.dbError - a.dbError )
    .slice( 0, 10 )
  if ( offenders.length === 0 ) {
    push( "All notes are within 1 dB of their target volume." )
  } else {
    push( `${ placement.overThreshold } note(s) exceed 1 dB (worst ${ offenders.length } listed):` )
    push()
    push( "| Track | Tick | Lateral | Error (dB) |" )
    push( "|---|---|---|---|" )
    for ( const p of offenders ) {
      push( `| ${ p.track } | ${ p.tick } | ${ p.dz } | ${ p.dbError.toFixed( 2 ) } |` )
    }
  }
  push()

  push( "## Warnings" )
  push()
  if ( input.warnings.length === 0 ) {
    push( "None." )
  } else {
    for ( const w of input.warnings ) push( `- ${ w }` )
  }
  push()

  return lines.join( "\n" )
}
